services:
  Gdnacho\Poob\:
    resource: '../../*'
    autowire: true
    autoconfigure: true
    exclude:
      - '../../Resources/config/*'
      - '../../Command/GenerateDocsCommand.php'

  Gdnacho\Poob\Command\GenerateDocsCommand:
    arguments:
      $router: '@router'
      $docsConfig: '%poob.docs%'
    tags: ['console.command']